// THE TYPE OF THE DATA THAT SHALL BE SAVED IN THE JSON FILES SHOULD BE CLASSES
// AS FOR ABOVE, RETRIEVED DATA SHALL BE IN AN ARRAY OF CLASSES
// 
// FOR THE RETRIEVE FUNCTIONS ADD THE OPTION TO RETURN AN OBJECT